/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ISrunAlarm: typeof import('~icons/srun/alarm')['default']
    ISrunBulb: typeof import('~icons/srun/bulb')['default']
    ISrunCaret: typeof import('~icons/srun/caret')['default']
    ISrunCheckmark: typeof import('~icons/srun/checkmark')['default']
    ISrunHome: typeof import('~icons/srun/home')['default']
    ISrunPlus: typeof import('~icons/srun/plus')['default']
    ISrunSearch: typeof import('~icons/srun/search')['default']
    ISrunTrashbin: typeof import('~icons/srun/trashbin')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
