version: 3
endpoint: https://rich-thrush-50.hasura.app
admin_secret: n65XrVlP0QwkLpdamfWnSkqy2NOwnuEwAlu1qxR2UH1Q541K0eo6jYtrcaxHDfYw
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
